### PR TITLE
null safety migration

### PR DESCRIPTION
**Pull request by Derrick56007**
also includes some formatting

### CODE REVIEW

**Comment by Derrick56007** [comment]
https://github.com/ra1u/redis-dart/issues/23

**Comment by ra1u** [comment]
Thank you for this.

It seems that there are some issues when I am running tests. Are you able to reproduce this?
In the mean time I have updated simple docker-compose script to run this tests in docker and you can find documentation and script.

https://github.com/ra1u/redis-dart/blob/master/test/docker/Readme.txt

and 
https://github.com/ra1u/redis-dart/blob/master/test/docker/docker-compose.yaml

**Comment by graphicbeacon** [comment]
@Derrick56007 @ra1u Thank you guys for your effort on this. When can we have this migration?

**Comment by ra1u** [comment]
@graphicbeacon  Can you merge what @Derrick56007 has done, run tests and send pull request?

**Comment by ra1u** [comment]
closed by https://github.com/ra1u/redis-dart/pull/28

**Pull request closed without merging**
